/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
    export interface GlobalComponents {
        AppMain: (typeof import("./../layout/components/AppMain/index.vue"))["default"];
        NavBar: (typeof import("./../layout/components/NavBar/index.vue"))["default"];
        LeftNavBar: (typeof import("./../layout/components/LeftNavBar/index.vue"))["default"];
        Breadcrumb: (typeof import("./../components/Breadcrumb/index.vue"))["default"];
        ElBacktop: (typeof import("element-plus/es"))["ElBacktop"];
        ElBreadcrumb: (typeof import("element-plus/es"))["ElBreadcrumb"];
        ElBreadcrumbItem: (typeof import("element-plus/es"))["ElBreadcrumbItem"];
        ElButton: (typeof import("element-plus/es"))["ElButton"];
        ElCard: (typeof import("element-plus/es"))["ElCard"];
        ElColorPicker: (typeof import("element-plus/es"))["ElColorPicker"];
        ElConfigProvider: (typeof import("element-plus/es"))["ElConfigProvider"];
        ElDivider: (typeof import("element-plus/es"))["ElDivider"];
        ElDrawer: (typeof import("element-plus/es"))["ElDrawer"];
        ElDropdown: (typeof import("element-plus/es"))["ElDropdown"];
        ElDropdownItem: (typeof import("element-plus/es"))["ElDropdownItem"];
        ElDropdownMenu: (typeof import("element-plus/es"))["ElDropdownMenu"];
        ElForm: (typeof import("element-plus/es"))["ElForm"];
        ElFormItem: (typeof import("element-plus/es"))["ElFormItem"];
        ElIcon: (typeof import("element-plus/es"))["ElIcon"];
        ElImage: (typeof import("element-plus/es"))["ElImage"];
        ElInput: (typeof import("element-plus/es"))["ElInput"];
        ElMenu: (typeof import("element-plus/es"))["ElMenu"];
        ElMenuItem: (typeof import("element-plus/es"))["ElMenuItem"];
        ElScrollbar: (typeof import("element-plus/es"))["ElScrollbar"];
        ElSubMenu: (typeof import("element-plus/es"))["ElSubMenu"];
        ElSwitch: (typeof import("element-plus/es"))["ElSwitch"];
        ElTag: (typeof import("element-plus/es"))["ElTag"];
        ElTooltip: (typeof import("element-plus/es"))["ElTooltip"];
        ElWatermark: (typeof import("element-plus/es"))["ElWatermark"];
        IEpClose: (typeof import("~icons/ep/close"))["default"];
        RouterLink: (typeof import("vue-router"))["RouterLink"];
        RouterView: (typeof import("vue-router"))["RouterView"];
        SvgIcon: (typeof import("./../components/SvgIcon/index.vue"))["default"];
        ItemBox: (typeof import("./../components/ItemBox/index.vue"))["default"];
        ContentBox: (typeof import("./../components/ContentBox/index.vue"))["default"];
    }
}
